# Data Wrangling

* pandas.merge: arguments are data frame names,on, left_on, right_on, how(join type), right_index [instead of right_on], left_index [instead od left_on]
* pandas.concat:glues/stacks. Arguments include keys, and the axis
* combine_first: overlapping data to fill in with another

In [1]:
from pandas import Series
import pandas as pd
import numpy as np

s1 = Series([0, 1], index=['a', 'b'])
s2 = Series([0, 1], index=['c', 'f'])
s3 = Series([0, 1], index=['v', 'b'])

pd.concat([s1,s2,s3],axis=0)

a    0
b    1
c    0
f    1
v    0
b    1
dtype: int64

In [2]:
# Reshaping and pivoting


data = pd.DataFrame(np.arange(6).reshape((2, 3)),
    index=pd.Index(['Ohio', 'Colorado'], name='state'),
    columns=pd.Index(['one', 'two', 'three'], name='number'))

result = data.stack()   #dropna is an argument similar to na.rm in R

result.unstack('state')

state   Ohio  Colorado
number
one        0         3
two        1         4
three      2         5

In [3]:
#renaming

data.rename(index=str.title,columns=str.upper)

number    ONE  TWO  THREE
state
Ohio        0    1      2
Colorado    3    4      5

In [4]:
# Discretization and binning

ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

bins = [18,25,30,35,40,45,50,70]

cats = pd.cut(ages,bins)  #precision argument to check the decimal points

print(cats.levels,cats.labels,)

print(pd.value_counts(cats))

(Index([u'(18, 25]', u'(25, 30]', u'(30, 35]', u'(35, 40]', u'(40, 45]',
       u'(45, 50]', u'(50, 70]'],
      dtype='object'), array([0, 0, 0, 1, 0, 0, 3, 2, 6, 4, 4, 2], dtype=int8))
(18, 25]    5
(40, 45]    2
(30, 35]    2
(50, 70]    1
(35, 40]    1
(25, 30]    1
(45, 50]    0
dtype: int64

C:\Users\unnikrishnan.s\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:9: FutureWarning: Accessing 'levels' is deprecated, use 'categories'
C:\Users\unnikrishnan.s\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:9: FutureWarning: 'labels' is deprecated. Use 'codes' instead

In [5]:
# detecting and filtering outliers

np.random.seed(12345)
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [6]:
data[(np.abs(data)>0).any(1)]

            0         1         2         3
0   -0.204708  0.478943 -0.519439 -0.555730
1    1.965781  1.393406  0.092908  0.281746
2    0.769023  1.246435  1.007189 -1.296221
3    0.274992  0.228913  1.352917  0.886429
4   -2.001637 -0.371843  1.669025 -0.438570
5   -0.539741  0.476985  3.248944 -1.021228
6   -0.577087  0.124121  0.302614  0.523772
7    0.000940  1.343810 -0.713544 -0.831154
8   -2.370232 -1.860761 -0.860757  0.560145
9   -1.265934  0.119827 -1.063512  0.332883
10  -2.359419 -0.199543 -1.541996 -0.970736
11  -1.307030  0.286350  0.377984 -0.753887
12   0.331286  1.349742  0.069877  0.246674
13  -0.011862  1.004812  1.327195 -0.919262
14  -1.549106  0.022185  0.758363 -0.660524
15   0.862580 -0.010032  0.050009  0.670216
16   0.852965 -0.955869 -0.023493 -2.304234
17  -0.652469 -1.218302 -1.332610  1.074623
18   0.723642  0.690002  1.001543 -0.503087
19  -0.622274 -0.921169 -0.726213  0.222896
20   0.051316 -1.157719  0.816707  0.433610
21   1.010737  1.824875 -0.997518  0.850591
22  -0.131578  0.912414  0.188211  2.169461
23  -0.114928  2.003697  0.029610  0.795253
24   0.118110 -0.748532  0.584970  0.152677
25  -1.565657 -0.562540 -0.032664 -0.929006
26  -0.482573 -0.036264  1.095390  0.980928
27  -0.589488  1.581700 -0.528735  0.457002
28   0.929969 -1.569271 -1.022487 -0.402827
29   0.220487 -0.193401  0.669158 -1.648985
..        ...       ...       ...       ...
970  1.140886  0.113279  0.206782 -1.460094
971 -1.523554 -0.590572 -0.324064  0.132262
972  0.097878  1.244456 -0.048534 -1.091849
973 -0.738296  0.115881  0.016253 -1.243078
974 -1.969172 -1.141360  0.405558 -0.521155
975 -0.813280 -0.461413  1.159668 -0.307670
976  0.669147  0.397355  0.612537  1.381155
977 -0.042541  1.182125  0.153036  0.075798
978  0.615651 -1.992291  0.963044  0.102469
979  0.359400  0.355787 -0.799366  1.120895
980 -0.261844 -0.474138 -0.112021 -0.285176
981 -0.136429  1.285628  0.753586  0.053410
982 -0.355393  0.790731  1.274794  0.233619
983 -1.316005  1.396082  0.336700  0.604880
984  0.675317 -0.060329  1.801953 -0.335099
985 -0.754114  0.650691  0.365401  1.367213
986 -0.105654 -0.001860  0.316802 -0.512542
987 -0.052736 -0.457225  2.452835 -1.050942
988 -0.172078  0.853049 -0.356263 -0.387002
989  0.881601  1.067288  1.079688  1.642339
990 -0.103672 -0.882949 -0.197357  1.336648
991  0.926782 -0.527103  0.633763  0.153988
992 -0.527754  0.815104 -0.677870 -1.466596
993  0.957144  0.377342 -0.383241  1.101972
994  1.221058 -0.326481  0.750008  0.604072
995  1.089085  0.251232 -1.451985  1.653126
996 -0.478509 -0.010663 -1.060881 -1.502870
997 -1.946267  1.013592  0.037333  0.133304
998 -1.293122 -0.322542 -0.782960 -0.303340
999  0.089987  0.292291  1.177706  0.882755

[1000 rows x 4 columns]

In [7]:
# Regex expressions

import re

f=open('C:\Users\unnikrishnan.s\Desktop\haha.txt','r')
text=f.read()

print(re.split('\s+',text))   #/s is a single sapce whereas s+ willbe multiple spaces

print(re.findall('\s',text))

['hscjhkdshofiuhosidh', 'dhfiuhsiduh', 'fiuahiuhfi', 'aishfo', 'hdsiufhiufghdsoiufhhiudshifuh', 'udhsiuhiofusdahofuhysoi', 'dufhiudhf', 'iudsh', 'iunc', 'iuniuiugsoudgvg', 'dshviuhds', 'iuvhiuh', 'iuhsdiuch', 'iushc', 'iushdc', 'oiushdiuah', 'ciuhs', 'diuhciusdhc', 'iudsnbciuscuygcyogaougp', 'yaug', 'g', 'couyagdsoycgoasyugdco', 'yaugc', 'doygdcousaygpi', 'ud', 'vpiuyhviushdvpiuhp', 'FYTF@hkjudhs.com', 'gdiwgjasod', 'tyaiuy@dquwy9.com', 'hjgSHAFDJHFSADUTYFWQVYHDYBQUIOWGDIUQWDB', 'UDWGHGIUG@OIQWDH.COM', 'iohsdiugib', 'djasghiug', 'kajdsh+uhqwiu@iuhsqiu.com', 'nsdjhnb%VH@dsiuh.com', 'uidgihuh%VJHGv@ls.co.in', 'uidgihuh%VJHGv@ls.co.uus', 'uidgihuh%VJHGv@ls.co.jqoijcc']
[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '\n', ' ', '\n', '\n', '\n', ' ', ' ', '\n', '\n', '\n', '\n', '\n']

In [8]:
#Using compile can save compile time when the pattern is being used multiple times.

pattern= r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z.]{2,5}'
regex=re.compile(pattern,flags=re.IGNORECASE)

regex.findall(text)

['FYTF@hkjudhs.com',
 'tyaiuy@dquwy9.com',
 'UDWGHGIUG@OIQWDH.COM',
 'kajdsh+uhqwiu@iuhsqiu.com',
 'nsdjhnb%VH@dsiuh.com',
 'uidgihuh%VJHGv@ls.co.in',
 'uidgihuh%VJHGv@ls.co.uus',
 'uidgihuh%VJHGv@ls.co.jqoij']

In [9]:
pattern2= r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

regex2=re.compile(pattern2,flags=re.IGNORECASE)

regex2.findall(text)

['FYTF@hkjudhs.com',
 'tyaiuy@dquwy9.com',
 'UDWGHGIUG@OIQWDH.COM',
 'kajdsh+uhqwiu@iuhsqiu.com',
 'nsdjhnb%VH@dsiuh.com',
 'uidgihuh%VJHGv@ls.co.in',
 'uidgihuh%VJHGv@ls.co.uus',
 'uidgihuh%VJHGv@ls.co.jqoi']

In [ ]:
print regex2.sub("REDACTED_INFO",text)

hscjhkdshofiuhosidh dhfiuhsiduh fiuahiuhfi aishfo hdsiufhiufghdsoiufhhiudshifuh udhsiuhiofusdahofuhysoi dufhiudhf iudsh iunc iuniuiugsoudgvg dshviuhds iuvhiuh iuhsdiuch iushc iushdc oiushdiuah ciuhs diuhciusdhc iudsnbciuscuygcyogaougp yaug g couyagdsoycgoasyugdco yaugc doygdcousaygpi ud vpiuyhviushdvpiuhp  REDACTED_INFO
gdiwgjasod REDACTED_INFO
hjgSHAFDJHFSADUTYFWQVYHDYBQUIOWGDIUQWDB
REDACTED_INFO
iohsdiugib djasghiug REDACTED_INFO

REDACTED_INFO
REDACTED_INFO
REDACTED_INFO
REDACTED_INFOjcc

In [ ]:
pattern3= r'([A-Z0-9._%+-]+)+@([A-Z0-9.-]+)+\.([A-Z]{2,4})' #paranthesis will seperate the three parsts

regex3=re.compile(pattern3,flags=re.IGNORECASE)

regex3.findall(text)